/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tciab
 */
public class interface_cadenas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interface_cadenas.class.getName());

    /**
     * Creates new form interface_cadenas
     */
    public interface_cadenas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        up_chiffre_4 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        nb_chiffre_exact = new javax.swing.JLabel();
        nb_chiffre_exact_res = new javax.swing.JLabel();
        nb_chiffre_trop_haut = new javax.swing.JLabel();
        nb_chiffre_trop_haut_res = new javax.swing.JLabel();
        nb_chiffre_trop_bas = new javax.swing.JLabel();
        nb_chiffre_trop_bas_res = new javax.swing.JLabel();
        tentatives_actuelles = new javax.swing.JLabel();
        tentatives_restantes = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("trouver le bon code en moins de 5 tentatives !");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 28, 266, -1));

        up_chiffre_1.setText("/\\");
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, -1));

            up_chiffre_2.setText("/\\");
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, -1));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 70, -1));

                    bouton_tester.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
                    bouton_tester.setText("Tester");
                    bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            bouton_testerActionPerformed(evt);
                        }
                    });
                    getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 133, 90, 30));

                    texte_chiffre_0.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                    texte_chiffre_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    texte_chiffre_0.setText("0");
                    texte_chiffre_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, 110));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 70, -1));

                        down_chiffre_4.setText("\\/");
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 70, -1));

                        down_chiffre_3.setText("\\/");
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 70, -1));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 70, -1));

                        down_chiffre_1.setText("\\/");
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, -1));

                        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        texte_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_3.setText("0");
                        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 70, 110));

                        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        texte_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_2.setText("0");
                        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 70, 110));

                        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        texte_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_1.setText("0");
                        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 70, 110));

                        nb_chiffre_exact.setText("Nombre de chiffres exacts :  ");
                        getContentPane().add(nb_chiffre_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, -1));

                        nb_chiffre_exact_res.setText("0");
                        getContentPane().add(nb_chiffre_exact_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 20, -1));

                        nb_chiffre_trop_haut.setText("Nombre de chiffres trop haut :  ");
                        getContentPane().add(nb_chiffre_trop_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, -1));

                        nb_chiffre_trop_haut_res.setText("0");
                        getContentPane().add(nb_chiffre_trop_haut_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 20, 20));

                        nb_chiffre_trop_bas.setText("Nombre de chiffres trop bas :  ");
                        getContentPane().add(nb_chiffre_trop_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, -1));

                        nb_chiffre_trop_bas_res.setText("0");
                        getContentPane().add(nb_chiffre_trop_bas_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 20, 20));

                        tentatives_actuelles.setText("Tentatives");
                        getContentPane().add(tentatives_actuelles, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 70, -1));

                        tentatives_restantes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                        tentatives_restantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        tentatives_restantes.setText("0/5");
                        tentatives_restantes.setAlignmentY(0.0F);
                        tentatives_restantes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                        getContentPane().add(tentatives_restantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 100, 50));

                        bouton_recommencer.setText("recommencer");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 140, 30));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interface_cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel nb_chiffre_exact;
    private javax.swing.JLabel nb_chiffre_exact_res;
    private javax.swing.JLabel nb_chiffre_trop_bas;
    private javax.swing.JLabel nb_chiffre_trop_bas_res;
    private javax.swing.JLabel nb_chiffre_trop_haut;
    private javax.swing.JLabel nb_chiffre_trop_haut_res;
    private javax.swing.JLabel tentatives_actuelles;
    private javax.swing.JLabel tentatives_restantes;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
