/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tciab
 */
public class interface_cadenas extends javax.swing.JFrame {
    
    private CadenasJeu jeu = new CadenasJeu();
    private int[] chiffres = {0, 0, 0, 0};

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interface_cadenas.class.getName());

    /**
     * Creates new form interface_cadenas
     */
    public interface_cadenas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        up_chiffre_4 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        nb_chiffre_exact = new javax.swing.JLabel();
        nb_chiffre_exact_res = new javax.swing.JLabel();
        nb_chiffre_trop_haut = new javax.swing.JLabel();
        nb_chiffre_trop_haut_res = new javax.swing.JLabel();
        nb_chiffre_trop_bas = new javax.swing.JLabel();
        nb_chiffre_trop_bas_res = new javax.swing.JLabel();
        tentatives_actuelles = new javax.swing.JLabel();
        tentatives_restantes = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        bouton_difficulte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("trouver le bon code en moins de 5 tentatives !");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 28, 266, -1));

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, -1));

            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, -1));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 70, -1));

                    bouton_tester.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
                    bouton_tester.setText("Tester");
                    bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            bouton_testerActionPerformed(evt);
                        }
                    });
                    getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 133, 90, 30));

                    texte_chiffre_0.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                    texte_chiffre_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    texte_chiffre_0.setText("0");
                    texte_chiffre_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, 110));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 70, -1));

                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 70, -1));

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 70, -1));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 70, -1));

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, -1));

                        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        texte_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_3.setText("0");
                        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 70, 110));

                        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        texte_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_2.setText("0");
                        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 70, 110));

                        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        texte_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_1.setText("0");
                        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 70, 110));

                        nb_chiffre_exact.setText("Nombre de chiffres exacts :  ");
                        getContentPane().add(nb_chiffre_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, -1));

                        nb_chiffre_exact_res.setText("0");
                        getContentPane().add(nb_chiffre_exact_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 20, -1));

                        nb_chiffre_trop_haut.setText("Nombre de chiffres trop haut :  ");
                        getContentPane().add(nb_chiffre_trop_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, -1));

                        nb_chiffre_trop_haut_res.setText("0");
                        getContentPane().add(nb_chiffre_trop_haut_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 20, 20));

                        nb_chiffre_trop_bas.setText("Nombre de chiffres trop bas :  ");
                        getContentPane().add(nb_chiffre_trop_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, -1));

                        nb_chiffre_trop_bas_res.setText("0");
                        getContentPane().add(nb_chiffre_trop_bas_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 20, 20));

                        tentatives_actuelles.setText("Tentatives");
                        getContentPane().add(tentatives_actuelles, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 70, -1));

                        tentatives_restantes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                        tentatives_restantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        tentatives_restantes.setText("0/5");
                        tentatives_restantes.setAlignmentY(0.0F);
                        tentatives_restantes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                        getContentPane().add(tentatives_restantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 100, 50));

                        bouton_recommencer.setText("recommencer");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 140, 30));

                        bouton_difficulte.setText("Difficulté");
                        bouton_difficulte.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_difficulteActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_difficulte, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 90, 30));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void rafraichirAffichage() {
    texte_chiffre_0.setText(String.valueOf(chiffres[0]));
    texte_chiffre_1.setText(String.valueOf(chiffres[1]));
    texte_chiffre_2.setText(String.valueOf(chiffres[2]));
    texte_chiffre_3.setText(String.valueOf(chiffres[3]));

    tentatives_restantes.setText(jeu.getTentatives() + "/" + jeu.getTentativesMax());
}
    private void resetAffichageResultats() {
    nb_chiffre_exact_res.setText("0");
    nb_chiffre_trop_haut_res.setText("0");
    nb_chiffre_trop_bas_res.setText("0");
    rafraichirAffichage();
}

    
    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
int[] resultat = jeu.tester(chiffres);

    nb_chiffre_exact_res.setText(String.valueOf(resultat[0]));
    nb_chiffre_trop_haut_res.setText(String.valueOf(resultat[1]));
    nb_chiffre_trop_bas_res.setText(String.valueOf(resultat[2]));

    rafraichirAffichage();

    if (resultat[0] == 4) {
        javax.swing.JOptionPane.showMessageDialog(this, "Bravo ! Vous avez trouvé le code !");
    } 
    else if (jeu.partieTerminee()) {
        javax.swing.JOptionPane.showMessageDialog(
    this,
    "Perdu ! Vous avez utilisé les " + jeu.getTentativesMax() + " tentatives."
);

    }        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
chiffres[2] = (chiffres[2] + 1) % 10;
    rafraichirAffichage();        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
chiffres[3] = (chiffres[3] + 1) % 10;
    rafraichirAffichage();        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
 chiffres[1] = (chiffres[1] + 9) % 10;
    rafraichirAffichage();        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
 jeu.genererCode();
    chiffres[0] = chiffres[1] = chiffres[2] = chiffres[3] = 0;

    nb_chiffre_exact_res.setText("0");
    nb_chiffre_trop_haut_res.setText("0");
    nb_chiffre_trop_bas_res.setText("0");

    rafraichirAffichage();        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
chiffres[2] = (chiffres[2] + 9) % 10;
    rafraichirAffichage();        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
chiffres[0] = (chiffres[0] + 1) % 10;
    rafraichirAffichage();
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
 chiffres[0] = (chiffres[0] + 9) % 10;
    rafraichirAffichage();        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
chiffres[1] = (chiffres[1] + 1) % 10;
    rafraichirAffichage();        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
chiffres[3] = (chiffres[3] + 9) % 10;
    rafraichirAffichage();        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_difficulteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_difficulteActionPerformed
    String[] choix = {"FACILE (15 essais)", "NORMAL (10 essais)", "IMPOSSIBLE (5 essais)"};

    int rep = javax.swing.JOptionPane.showOptionDialog(
            this,
            "Choisis une difficulté (la partie redémarre) :",
            "Difficulté",
            javax.swing.JOptionPane.DEFAULT_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            choix,
            choix[1]
    );
//2Z2Z2
    if (rep == -1) return; // l'utilisateur a fermé la fenêtre

    CadenasJeu.Difficulte d;
    if (rep == 0) d = CadenasJeu.Difficulte.FACILE;
    else if (rep == 1) d = CadenasJeu.Difficulte.NORMAL;
    else d = CadenasJeu.Difficulte.IMPOSSIBLE;

    // applique la difficulté (et redémarre la partie)
    jeu.setDifficulte(d);

    // reset chiffres affichés
    chiffres[0] = chiffres[1] = chiffres[2] = chiffres[3] = 0;

    // met à jour le texte du bouton
    bouton_difficulte.setText("Difficulté : " + d.name());

    // reset affichage (résultats + tentatives)
    resetAffichageResultats();   // TODO add your handling code here:
    }//GEN-LAST:event_bouton_difficulteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interface_cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_difficulte;
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel nb_chiffre_exact;
    private javax.swing.JLabel nb_chiffre_exact_res;
    private javax.swing.JLabel nb_chiffre_trop_bas;
    private javax.swing.JLabel nb_chiffre_trop_bas_res;
    private javax.swing.JLabel nb_chiffre_trop_haut;
    private javax.swing.JLabel nb_chiffre_trop_haut_res;
    private javax.swing.JLabel tentatives_actuelles;
    private javax.swing.JLabel tentatives_restantes;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
