/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tciab
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private java.util.ArrayList<Question> listeQuestions = new java.util.ArrayList<>();
    private int indexQuestionCourante = 0;
    private int score = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */
    public FenetreQuiz() {
         initComponents();

    // Ajout de plusieurs questions
    listeQuestions.add(new Question(
            "Quelle est la capitale de la France ?",
            "Paris", "Lyon", "Marseille", "Nice",
            1
    ));
    listeQuestions.add(new Question(
            "Combien font 3 × 4 ?",
            "7", "12", "9", "3",
            2
    ));
    listeQuestions.add(new Question(
            "Quel est le plus grand océan ?",
            "Atlantique", "Arctique", "Pacifique", "Indien",
            3
    ));
    listeQuestions.add(new Question(
            "Qui a peint la Joconde ?",
            "Van Gogh", "Picasso", "Michel-Ange", "Da Vinci",
            4
    ));
    listeQuestions.add(new Question(
            "En quelle année est sortie Java ?",
            "1995", "2001", "1989", "2010",
            1
    ));

    afficherQuestionCourante(); // >>> charge la première question
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_question = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2_feedback = new javax.swing.JLabel();
        jButton5_Qsuivant = new javax.swing.JButton();
        jLabel3_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_question.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1_question.setText("question");
        getContentPane().add(jLabel1_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 400, 60));

        jButton1.setForeground(new java.awt.Color(51, 102, 255));
        jButton1.setText("Rep1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jButton2.setForeground(new java.awt.Color(204, 0, 255));
        jButton2.setText("Rep2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Rep3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jButton4.setForeground(new java.awt.Color(51, 204, 0));
        jButton4.setText("Rep4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel2_feedback.setText("feedback");
        getContentPane().add(jLabel2_feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jButton5_Qsuivant.setText("Question Suivante");
        jButton5_Qsuivant.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5_Qsuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_QsuivantActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5_Qsuivant, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel3_score.setText("jlab3 score");
        getContentPane().add(jLabel3_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
verifierReponse(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
verifierReponse(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
verifierReponse(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
verifierReponse(4);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5_QsuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_QsuivantActionPerformed
    indexQuestionCourante++;

    if (indexQuestionCourante < listeQuestions.size()) {
        afficherQuestionCourante();
    } else {
        jLabel2_feedback.setText("Quiz terminé ! Score final : " + score);
        jButton5_Qsuivant.setEnabled(false);
    }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5_QsuivantActionPerformed

    private void afficherQuestionCourante() {
    Question q = listeQuestions.get(indexQuestionCourante);

    jLabel1_question.setText(q.getIntitule());
    jButton1.setText(q.getProposition1());
    jButton2.setText(q.getProposition2());
    jButton3.setText(q.getProposition3());
    jButton4.setText(q.getProposition4());

    jLabel2_feedback.setText(""); // effacer message précédent

    // Réactiver les boutons
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
    jButton3.setEnabled(true);
    jButton4.setEnabled(true);

    // Afficher score actuel
    jLabel3_score.setText("Score : " + score);
}
    private void verifierReponse(int numeroChoisi) {
    Question q = listeQuestions.get(indexQuestionCourante);

    if (numeroChoisi == q.getIndexBonneReponse()) {
        jLabel2_feedback.setText("Bonne réponse !");
        score++;
        jLabel3_score.setText("Score : " + score);
    } else {
        jLabel2_feedback.setText("Mauvaise réponse !");
    }

    // Désactiver les 4 boutons
    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5_Qsuivant;
    private javax.swing.JLabel jLabel1_question;
    private javax.swing.JLabel jLabel2_feedback;
    private javax.swing.JLabel jLabel3_score;
    // End of variables declaration//GEN-END:variables
}
